'use client';
import {useState} from 'react';
const rounds=[{name:'Warm to cool',colors:['#c88083','#c77e96','#b980ae','#a485bd','#8d8fc3','#799bc1','#71a7b5','#77afa3']},{name:'Green to blue',colors:['#a3ad78','#8fb185','#7bb294','#70b0a7','#73abb8','#80a3c3','#929ac8','#a58fbd']},{name:'Orange to rose',colors:['#c39470','#c68c78','#c88584','#c77f92','#bf7e9f','#b680ad','#a785b8','#958bbc']}];
// Custom sRGB exercises, not calibrated clinical test stimuli.
const shuffled=(count:number)=>{const a=Array.from({length:count},(_,i)=>i);for(let i=a.length-1;i>0;i--){const random=new Uint32Array(1);crypto.getRandomValues(random);const j=random[0]%(i+1);[a[i],a[j]]=[a[j],a[i]]}return a};
type Result={name:string;matched:number;total:number};
export default function Screening(){const [ready,setReady]=useState(false);const [stage,setStage]=useState<'setup'|'test'|'result'>('setup');const [round,setRound]=useState(0);const [pool,setPool]=useState<number[]>([]);const [order,setOrder]=useState<number[]>([]);const [results,setResults]=useState<Result[]>([]);const [notice,setNotice]=useState('');
const current=rounds[round];const inner=current.colors.slice(1,-1);const start=()=>{setRound(0);setPool(shuffled(6));setOrder([]);setResults([]);setNotice('');setStage('test')};
const choose=(id:number)=>{setPool(p=>p.filter(x=>x!==id));setOrder(o=>[...o,id]);setNotice('Tile added to your sequence.')};const undo=(index:number)=>{const id=order[index];setOrder(o=>o.filter((_,i)=>i!==index));setPool(p=>[...p,id]);setNotice('Tile returned to the choices.')};
const next=()=>{const score=order.filter((id,i)=>id===i).length;setResults(r=>[...r,{name:current.name,matched:score,total:inner.length}]);setNotice('');if(round===rounds.length-1){setStage('result')}else{setRound(r=>r+1);setPool(shuffled(6));setOrder([])}};
if(stage==='result'){const total=results.reduce((s,r)=>s+r.matched,0);return <section className="form-card vision-prep"><span className="eyebrow">Your exercise summary</span><h2>{total} of 18 positions matched.</h2><p>This compares your tile order with the intended sequence for these custom exercises. It is not a clinical score, a pass/fail result, or a measurement of how severe a color-vision difference might be.</p><div className="vision-results">{results.map(r=><div key={r.name}><strong>{r.name}</strong><span>{r.matched} / {r.total} positions</span></div>)}</div><div className="status"><strong>Always check with an eye doctor.</strong><br/>A high score does not rule out color-vision deficiency. A low score may reflect screen settings, lighting, or the task itself. Only professional testing can clarify your color vision.</div><p>These exercises are not clinically validated and cannot identify red-green or blue-yellow deficiency, its type, or severity.</p><button className="button" onClick={start}>Try again</button><p className="vision-small">Your answers stay in this page’s memory. They are not sent to the owner or saved to your account.</p></section>}
if(stage==='test')return <section className="form-card vision-prep vision-exercise"><div className="vision-round"><span className="eyebrow">Exercise {round+1} of 3</span><span>{order.length} of 6 tiles placed</span></div><progress value={round} max={3} aria-label="Exercises completed"/><h2>Build a smooth color sequence.</h2><p>Choose the tiles in order to make the smoothest transition from the fixed first color to the fixed last color. No timer—take your time.</p><div className="vision-sequence" aria-label="Your color sequence"><div className="vision-anchor"><div style={{background:current.colors[0]}}/><span>Start</span></div>{Array.from({length:6},(_,i)=><div className="vision-slot" key={i}>{order[i]!==undefined?<button style={{background:inner[order[i]]}} onClick={()=>undo(i)} aria-label={`Remove tile from position ${i+1}`} title="Return this tile to the choices"/>:<div className="vision-placeholder" aria-label={`Empty position ${i+1}`}/>}<span>{i+1}</span></div>)}<div className="vision-anchor"><div style={{background:current.colors.at(-1)}}/><span>End</span></div></div><p className="vision-small">Select a tile below to add it next. Select a placed tile to return it.</p><div className="vision-choices" aria-label="Available tiles">{pool.map((id,i)=><button key={id} style={{background:inner[id]}} aria-label={`Choose available tile ${i+1}`} onClick={()=>choose(id)}/>)}</div><p className="vision-small" role="status" aria-live="polite">{notice||'Choose your first tile.'}</p><div className="vision-actions"><button className="button" disabled={order.length!==6} onClick={next}>{round===2?'See my results':'Next exercise'}</button><button className="text-button" onClick={()=>{setStage('setup');setReady(false)}}>Exit exercise</button></div><p className="vision-small">Custom, unvalidated color-ordering exercise. Not a medical diagnosis.</p></section>;
return <section className="form-card vision-prep"><span className="eyebrow">Before you begin</span><h2>Explore your color vision.<br/>Right here.</h2><p>Three short color-ordering exercises. Free, no signup, and no external test website.</p><ol><li>Turn off Night Shift, True Tone, blue-light modes, and accessibility color filters for the exercise. Restore your preferred settings afterward.</li><li>Use comfortable brightness, reduce glare, and look straight at the screen.</li><li>Use your usual clear prescription lenses if needed. Avoid tinted lenses or color-enhancing glasses.</li></ol><div className="status"><strong>This is an educational self-check.</strong><br/>These custom exercises are not clinically validated. Screen preparation cannot make your display a calibrated medical instrument. Always check concerns with an eye doctor.</div><label className="vision-consent"><input type="checkbox" checked={ready} onChange={e=>setReady(e.target.checked)}/><span>I understand that this exercise cannot diagnose color blindness and that I should check with an eye doctor.</span></label><button className="button" onClick={start} disabled={!ready}>Start the free color check</button><p className="vision-small">All exercises and results run inside this page. Your answers are not collected or saved.</p></section>}
