'use client';
import {useState,useEffect,useCallback} from 'react';
type Post={id:string;userId:string;name:string;body:string;createdAt:number};
export default function Board({userId,service}:{userId:string|null,service:string|null}){const [posts,setPosts]=useState<Post[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [body,setBody]=useState('');const [busy,setBusy]=useState(false);const [notice,setNotice]=useState('');const prefix=service?`[${service}]\n`:'';const maxLength=2000-prefix.length;
const load=useCallback(async()=>{setLoading(true);try{const r=await fetch('/api/posts');const d=await r.json() as {error?:string,posts:Post[],post:Post};if(!r.ok)throw Error(d.error||"Request failed.");setPosts(d.posts);setError('')}catch(e){setError(e instanceof Error?e.message:'Could not load messages.')}finally{setLoading(false)}},[]);
const publish=useCallback(async(value:string)=>{if(!userId)throw Error('Please sign in to post.');if(typeof value!=='string'||value.trim().length<3||value.trim().length>maxLength)throw Error('Write a message between 3 and 2,000 characters.');setBusy(true);try{const r=await fetch('/api/posts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({body:prefix+value.trim()})});const d=await r.json() as {error?:string,posts:Post[],post:Post};if(!r.ok)throw Error(d.error||"Request failed.");setPosts(p=>[d.post,...p]);setBody('');setNotice(service?'Your service thread is published.':'Your message is published.');return {id:d.post.id,status:'published'};}finally{setBusy(false)}},[userId,prefix,maxLength,service]);
useEffect(()=>{void load()},[load]);
useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:unknown)=>Promise<void>}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();void Promise.resolve(context.registerTool({name:'publish_community_message',title:'Publish a community message',description:'Publish a message under the signed-in account and update the visible community board.',inputSchema:{type:'object',properties:{body:{type:'string',minLength:3,maxLength:2000}},required:['body'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async(input:{body:string})=>publish(input.body)},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort()},[publish]);
async function submit(e:React.FormEvent){e.preventDefault();setError('');try{await publish(body)}catch(e){setError(e instanceof Error?e.message:'Could not post.')}}async function remove(id:string){setError('');try{const r=await fetch('/api/posts',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});const d=await r.json() as {error?:string,posts:Post[],post:Post};if(!r.ok)throw Error(d.error||"Request failed.");setPosts(p=>p.filter(x=>x.id!==id));setNotice('Your message was deleted.')}catch(e){setError(e instanceof Error?e.message:'Could not delete.')}}
return <>{userId&&<form id="new-thread" className="form-card" onSubmit={submit}>{service&&<><h2 style={{fontSize:"1.8rem"}}>Let’s talk about {service.toLowerCase()}.</h2><p>Your thread will be posted publicly on the community board.</p><div className="tags"><span>{service}</span></div></>}<label>{service?"Start your thread":"Share an idea"}<textarea value={body} onChange={e=>setBody(e.target.value)} minLength={3} maxLength={maxLength} required placeholder={service?"What would you like to explore? Share your idea or ask a question…":"Introduce yourself or tell us what you’re working on…"}/></label><button className="button" disabled={busy}>{busy?'Publishing…':service?'Publish thread':'Publish message'}</button></form>}{notice&&<p className="status" role="status">{notice}</p>}{error&&<p className="status error" role="alert">{error} <button onClick={load}>Retry loading</button></p>}{loading?<p role="status">Loading conversations…</p>:posts.length===0?<p className="empty">A fresh page. Be the first to start a conversation.</p>:posts.map(p=><article className="post" key={p.id}><div className="post-meta"><strong>{p.name}</strong><time dateTime={new Date(p.createdAt).toISOString()}>{new Date(p.createdAt).toLocaleDateString('en-US',{year:'numeric',month:'short',day:'numeric',timeZone:'America/Los_Angeles'})}</time></div>{p.body.match(/^\[(Brand strategy|Visual identity|Digital experiences)\]\n/)?<><div className="tags" style={{marginTop:16}}><span>{p.body.split("\n")[0].slice(1,-1)} thread</span></div><p>{p.body.substring(p.body.indexOf("\n")+1)}</p></>:<p>{p.body}</p>}{p.userId===userId&&<button className="delete" onClick={()=>remove(p.id)}>Delete your message</button>}</article>)}</>}
