'use client';
import {useEffect,useState} from 'react';
export default function SiteMotion(){const [paused,setPaused]=useState(false);
useEffect(()=>{const preference=window.matchMedia('(prefers-reduced-motion: reduce)');if(preference.matches)setPaused(true);const sync=()=>setPaused(preference.matches);preference.addEventListener('change',sync);return()=>preference.removeEventListener('change',sync)},[]);
useEffect(()=>{document.documentElement.classList.toggle('motion-paused',paused);const reduce=window.matchMedia('(prefers-reduced-motion: reduce)').matches;if(paused||reduce)return;
const targets=Array.from(document.querySelectorAll<HTMLElement>('.feature,.feature-copy,.approach h2,.three article,.cta,.service-row,.contact-info,.form-card,.account-card,.post'));
const observer=new IntersectionObserver(entries=>{for(const entry of entries)if(entry.isIntersecting){entry.target.classList.add('revealed');observer.unobserve(entry.target)}},{threshold:.12});targets.forEach(el=>{el.classList.add('reveal-ready');observer.observe(el)});
let frame=0;const progress=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{const range=document.documentElement.scrollHeight-window.innerHeight;document.documentElement.style.setProperty('--scroll-progress',String(range>0?window.scrollY/range:0))})};window.addEventListener('scroll',progress,{passive:true});progress();
const fine=window.matchMedia('(hover:hover) and (pointer:fine)').matches;const tilts=fine?Array.from(document.querySelectorAll<HTMLElement>('[data-tilt]')):[];
const move=(event:PointerEvent)=>{const el=event.currentTarget as HTMLElement;const r=el.getBoundingClientRect();el.style.setProperty('--tilt-x',`${((event.clientY-r.top)/r.height-.5)*-6}deg`);el.style.setProperty('--tilt-y',`${((event.clientX-r.left)/r.width-.5)*6}deg`)};const reset=(event:PointerEvent)=>{const el=event.currentTarget as HTMLElement;el.style.setProperty('--tilt-x','0deg');el.style.setProperty('--tilt-y','0deg')};tilts.forEach(el=>{el.addEventListener('pointermove',move);el.addEventListener('pointerleave',reset)});
return()=>{observer.disconnect();targets.forEach(el=>el.classList.remove('reveal-ready','revealed'));window.removeEventListener('scroll',progress);cancelAnimationFrame(frame);tilts.forEach(el=>{el.removeEventListener('pointermove',move);el.removeEventListener('pointerleave',reset);el.style.removeProperty('--tilt-x');el.style.removeProperty('--tilt-y')})}},[paused]);
return <><div className="reading-progress" aria-hidden="true"/><button className="motion-control" aria-pressed={paused} onClick={()=>setPaused(p=>!p)} title="Control decorative animations">{paused?'Enable motion':'Pause motion'}</button></>}
